modLoader="javafml"
loaderVersion="[4,)"
license="All rights reserved"
issueTrackerURL="https://github.com/vadis365/MagmaMonsters/issues"

[[mods]] #mandatory
modId="magma_monsters"
version="2.0.0"
displayName="Magma Monsters"
displayURL="https://github.com/vadis365/MagmaMonsters"
credits="Thanks to Shin00w for creepy sounds."
authors="vadis365"
description='''
A Mod that adds some Magma Monsters.'''
[[dependencies.magma_monsters]]
modId="neoforge"
required=true
versionRange="[21.1.0,)"
ordering="NONE"
side="BOTH"